name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: xcodebuild -scheme Dux2 -destination 'platform=iOS Simulator,OS=13.4,name=iPhone 12' || xcodebuild -scheme Dux -destination 'platform=iOS Simulator,OS=13.5,name=iPhone 12'
